### ISSUE TITLE
Cannot update a component (`Donut`) while rendering a different component (`Knob`)

### ISSUE THREAD

**Issue by atsukoba** [pavelkukov/react-dial-knob#5]
thanks for great package.

I faced the error when using the `<Donut>` component by changing props/state value

### error msg and trace

```
Warning: Cannot update a component (`Donut`) while rendering a different component (`Knob`). To locate the bad setState() call inside `Knob`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Knob (created by Donut)
    in div (created by SkinWrap)
    in SkinWrap (created by Donut)
```

**Comment by atsukoba** [comment]
this warning is introduced from `React 16.13`

**Comment by pavelkukov** [comment]
Hi @atsukoba ,
Thank you for raising this issue. I was able to reproduce it.
Now is fixed with `react-dial-knob@1.1.7`. 
Working demo with react@16.13 in codepen - https://codepen.io/pavelkukov/pen/MWjBNNX
Also a demo with react@17.0.1 - https://codepen.io/pavelkukov/pen/xxGgZvL?editors=0010


Please let me know if 1.1.7 works for you!

Best regards,
Pavel

**Comment by atsukoba** [comment]
@pavelkukov Thanks for replying and fixing the issue I reported!!

I checked and confirmed that the new version works on my environment. thanks.

**Comment by pavelkukov** [comment]
Thank you, @atsukoba ! I'm closing this. :)
